In [2]:
%matplotlib inline

import quandl as ql
import numpy as np
import pandas as pd
import matplotlib.pylab as plt
import csv

ql.ApiConfig.api_key = "y-zCjPnDPkRm_5tTzGRY"

In [40]:
with open("sp500.csv", 'r') as sp500:
    reader = csv.reader(sp500)
    sp500_list = next(reader)

In [42]:
print(sp500_list)

['ABT', 'ABBV', 'ACN', 'ACE', 'ADBE', 'ADT', 'AAP', 'AES', 'AET', 'AFL', 'AMG', 'A', 'GAS', 'APD', 'ARG', 'AKAM', 'AA', 'AGN', 'ALXN', 'ALLE', 'ADS', 'ALL', 'ALTR', 'MO', 'AMZN', 'AEE', 'AAL', 'AEP', 'AXP', 'AIG', 'AMT', 'AMP', 'ABC', 'AME', 'AMGN', 'APH', 'APC', 'ADI', 'AON', 'APA', 'AIV', 'AMAT', 'ADM', 'AIZ', 'T', 'ADSK', 'ADP', 'AN', 'AZO', 'AVGO', 'AVB', 'AVY', 'BHI', 'BLL', 'BAC', 'BK', 'BCR', 'BXLT', 'BAX', 'BBT', 'BDX', 'BBBY', 'BRK_B', 'BBY', 'BLX', 'HRB', 'BA', 'BWA', 'BXP', 'BSK', 'BMY', 'BRCM', 'BF_B', 'CHRW', 'CA', 'CVC', 'COG', 'CAM', 'CPB', 'COF', 'CAH', 'HSIC', 'KMX', 'CCL', 'CAT', 'CBG', 'CBS', 'CELG', 'CNP', 'CTL', 'CERN', 'CF', 'SCHW', 'CHK', 'CVX', 'CMG', 'CB', 'CI', 'XEC', 'CINF', 'CTAS', 'CSCO', 'C', 'CTXS', 'CLX', 'CME', 'CMS', 'COH', 'KO', 'CCE', 'CTSH', 'CL', 'CMCSA', 'CMA', 'CSC', 'CAG', 'COP', 'CNX', 'ED', 'STZ', 'GLW', 'COST', 'CCI', 'CSX', 'CMI', 'CVS', 'DHI', 'DHR', 'DRI', 'DVA', 'DE', 'DLPH', 'DAL', 'XRAY', 'DVN', 'DO', 'DTV', 'DFS', 'DISCA', 'DISCK', 'DG', 'DLTR', 'D', 'DOV', 'DOW', 'DPS', 'DTE', 'DD', 'DUK', 'DNB', 'ETFC', 'EMN', 'ETN', 'EBAY', 'ECL', 'EIX', 'EW', 'EA', 'EMC', 'EMR', 'ENDP', 'ESV', 'ETR', 'EOG', 'EQT', 'EFX', 'EQIX', 'EQR', 'ESS', 'EL', 'ES', 'EXC', 'EXPE', 'EXPD', 'ESRX', 'XOM', 'FFIV', 'FB', 'FAST', 'FDX', 'FIS', 'FITB', 'FSLR', 'FE', 'FSIV', 'FLIR', 'FLS', 'FLR', 'FMC', 'FTI', 'F', 'FOSL', 'BEN', 'FCX', 'FTR', 'GME', 'GPS', 'GRMN', 'GD', 'GE', 'GGP', 'GIS', 'GM', 'GPC', 'GNW', 'GILD', 'GS', 'GT', 'GOOGL', 'GOOG', 'GWW', 'HAL', 'HBI', 'HOG', 'HAR', 'HRS', 'HIG', 'HAS', 'HCA', 'HCP', 'HCN', 'HP', 'HES', 'HPQ', 'HD', 'HON', 'HRL', 'HSP', 'HST', 'HCBK', 'HUM', 'HBAN', 'ITW', 'IR', 'INTC', 'ICE', 'IBM', 'IP', 'IPG', 'IFF', 'INTU', 'ISRG', 'IVZ', 'IRM', 'JEC', 'JBHT', 'JNJ', 'JCI', 'JOY', 'JPM', 'JNPR', 'KSU', 'K', 'KEY', 'GMCR', 'KMB', 'KIM.KMI', 'KLAC', 'KSS', 'KRFT', 'KR', 'LB', 'LLL', 'LH', 'LRCX', 'LM', 'LEG', 'LEN', 'LVLT', 'LUK', 'LLY', 'LNC', 'LLTC', 'LMT', 'L', 'LOW', 'LYB', 'MTB', 'MAC', 'M', 'MNK', 'MRO', 'MPC', 'MAR', 'MMC', 'MLM', 'MAS', 'MA', 'MAT', 'MKC', 'MCD', 'MHFI', 'MCK', 'MJN', 'MMV', 'MDT', 'MRK', 'MET', 'KORS', 'MCHP', 'MU', 'MSFT', 'MHK', 'TAP', 'MDLZ', 'MON', 'MNST', 'MCO', 'MS', 'MOS', 'MSI', 'MUR', 'MYL', 'NDAQ', 'NOV', 'NAVI', 'NTAP', 'NFLX', 'NWL', 'NFX', 'NEM', 'NWSA', 'NEE', 'NLSN', 'NKE', 'NI', 'NE', 'NBL', 'JWN', 'NSC', 'NTRS', 'NOC', 'NRG', 'NUE', 'NVDA', 'ORLY', 'OXY', 'OMC', 'OKE', 'ORCL', 'OI', 'PCAR', 'PLL', 'PH', 'PDCO', 'PAYX', 'PNR', 'PBCT', 'POM', 'PEP', 'PKI', 'PRGO', 'PFE', 'PCG', 'PM', 'PSX', 'PNW', 'PXD', 'PBI', 'PCL', 'PNC', 'RL', 'PPG', 'PPL', 'PX', 'PCP', 'PCLN', 'PFG', 'PG', 'PGR', 'PLD', 'PRU', 'PEG', 'PSA', 'PHM', 'PVH', 'QRVO', 'PWR', 'QCOM', 'DGX', 'RRC', 'RTN', 'O', 'RHT', 'REGN', 'RF', 'RSG', 'RAI', 'RHI', 'ROK', 'COL', 'ROP', 'ROST', 'RLC', 'R', 'CRM', 'SNDK', 'SCG', 'SLB', 'SNI', 'STX', 'SEE', 'SRE', 'SHW', 'SIAL', 'SPG', 'SWKS', 'SLG', 'SJM', 'SNA', 'SO', 'LUV', 'SWN', 'SE', 'STJ', 'SWK', 'SPLS', 'SBUX', 'HOT', 'STT', 'SRCL', 'SYK', 'STI', 'SYMC', 'SYY', 'TROW', 'TGT', 'TEL', 'TE', 'TGNA', 'THC', 'TDC', 'TSO', 'TXN', 'TXT', 'HSY', 'TRV', 'TMO', 'TIF', 'TWX', 'TWC', 'TJK', 'TMK', 'TSS', 'TSCO', 'RIG', 'TRIP', 'FOXA', 'TSN', 'TYC', 'UA', 'UNP', 'UNH', 'UPS', 'URI', 'UTX', 'UHS', 'UNM', 'URBN', 'VFC', 'VLO', 'VAR', 'VTR', 'VRSN', 'VZ', 'VRTX', 'VIAB', 'V', 'VNO', 'VMC', 'WMT', 'WBA', 'DIS', 'WM', 'WAT', 'ANTM', 'WFC', 'WDC', 'WU', 'WY', 'WHR', 'WFM', 'WMB', 'WEC', 'WYN', 'WYNN', 'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZBH', 'ZION', 'ZTS']

In [5]:
def get_close_price(ticker, sdate, edate):
    data = ql.get("WIKI/"+ticker, 
                      start_date=sdate, 
                      end_date=edate,
                      returns="pandas")['Adj. Close']
    return data

In [43]:
sdate = "2007-01-01"
edate = "2017-01-01"
data = []
colums_name = []
for ticker in sp500_list:
    try:
        data.append(get_close_price(ticker, sdate, edate))
        colums_name.append(ticker)
    except:
        print("Ticker: ", ticker, "was not found")

Ticker:  BSK was not found
Ticker:  EA was not found
Ticker:  FSIV was not found
Ticker:  KIM.KMI was not found
Ticker:  MMV was not found
Ticker:  RLC was not found
Ticker:  TJK was not found

In [17]:
df = pd.concat(data, axis=1)
df.columns = colums_name

In [50]:
def split_dataset(df, nb_split=3):
    lenght = len(df)

2518

In [6]:
sdate = "2017-01-01"
edate = "2017-03-01"
data = ql.get("WIKI/"+"AAPL", 
                      start_date=sdate, 
                      end_date=edate,
                      returns="pandas")

In [9]:
data

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2017-01-03,115.800,116.3300,114.7600,116.150,28781865.0,0.00,1.0,114.369701,114.893155,113.342546,114.715378,28781865.0
2017-01-04,115.850,116.5100,115.7500,116.020,21118116.0,0.00,1.0,114.419083,115.070931,114.320318,114.586983,21118116.0
2017-01-05,115.920,116.8642,115.8100,116.610,22193587.0,0.00,1.0,114.488219,115.420756,114.379577,115.169696,22193587.0
2017-01-06,116.780,118.1600,116.4700,117.910,31751900.0,0.00,1.0,115.337596,116.700551,115.031425,116.453639,31751900.0
2017-01-09,117.950,119.4300,117.9400,118.990,33561948.0,0.00,1.0,116.493145,117.954865,116.483269,117.520300,33561948.0
2017-01-10,118.770,119.3800,118.3000,119.110,24462051.0,0.00,1.0,117.303017,117.905483,116.838822,117.638817,24462051.0
2017-01-11,118.740,119.9300,118.6000,119.750,27588593.0,0.00,1.0,117.273388,118.448689,117.135117,118.270913,27588593.0
2017-01-12,118.895,119.3000,118.2100,119.250,27086220.0,0.00,1.0,117.426473,117.826471,116.749934,117.777088,27086220.0
2017-01-13,119.110,119.6200,118.8100,119.040,26111948.0,0.00,1.0,117.638817,118.142518,117.342523,117.569682,26111948.0
2017-01-17,118.340,120.2400,118.2200,120.000,34439843.0,0.00,1.0,116.878328,118.754860,116.759810,118.517825,34439843.0
2017-01-18,120.000,120.5000,119.7100,119.990,23712961.0,0.00,1.0,118.517825,119.011649,118.231407,118.507948,23712961.0
2017-01-19,119.400,120.0900,119.3700,119.780,25597291.0,0.00,1.0,117.925236,118.606713,117.895606,118.300542,25597291.0
2017-01-20,120.450,120.4500,119.7346,120.000,32597892.0,0.00,1.0,118.962267,118.962267,118.255703,118.517825,32597892.0
2017-01-23,120.000,120.8100,119.7700,120.080,22050218.0,0.00,1.0,118.517825,119.317820,118.290666,118.596837,22050218.0
2017-01-24,119.550,120.1000,119.5000,119.970,23211038.0,0.00,1.0,118.073383,118.616590,118.024000,118.488195,23211038.0
2017-01-25,120.420,122.1000,120.2800,121.880,32586673.0,0.00,1.0,118.932637,120.591887,118.794366,120.374604,32586673.0
2017-01-26,121.670,122.4400,121.6000,121.940,26337576.0,0.00,1.0,120.167198,120.927687,120.098062,120.433863,26337576.0
2017-01-27,122.140,122.3500,121.6000,121.950,20562944.0,0.00,1.0,120.631393,120.838799,120.098062,120.443739,20562944.0
2017-01-30,120.930,121.6300,120.6600,121.630,30377503.0,0.00,1.0,119.436338,120.127692,119.169673,120.127692,30377503.0
2017-01-31,121.150,121.3900,120.6200,121.350,49200993.0,0.00,1.0,119.653620,119.890656,119.130167,119.851150,49200993.0
2017-02-01,127.030,130.4900,127.0100,128.750,111985040.0,0.00,1.0,125.460994,128.878258,125.441241,127.159749,111985040.0
2017-02-02,127.975,129.3900,127.7800,128.530,33710411.0,0.00,1.0,126.394322,127.791844,126.201730,126.942467,33710411.0
2017-02-03,128.310,129.1900,128.1600,129.080,24507301.0,0.00,1.0,126.725184,127.594315,126.577037,127.485673,24507301.0
2017-02-06,129.130,130.5000,128.9000,130.290,26845924.0,0.00,1.0,127.535056,128.888134,127.307897,128.680728,26845924.0
2017-02-07,130.540,132.0900,130.4500,131.530,38183841.0,0.00,1.0,128.927640,130.458496,128.838752,129.905412,38183841.0
2017-02-08,131.350,132.2200,131.2200,132.040,23004072.0,0.00,1.0,129.727636,130.586890,129.599241,130.409113,23004072.0
2017-02-09,131.650,132.4450,131.1200,132.420,28349859.0,0.57,1.0,130.583616,131.372177,130.057909,131.347379,28349859.0
2017-02-10,132.460,132.9400,132.0500,132.120,20065458.0,0.00,1.0,131.387055,131.863167,130.980376,131.049809,20065458.0
2017-02-13,133.080,133.8200,132.7500,133.290,23035421.0,0.00,1.0,132.002033,132.736039,131.674706,132.210332,23035421.0
2017-02-14,133.470,135.0900,133.2500,135.020,33226223.0,0.00,1.0,132.388874,133.995752,132.170656,133.926319,33226223.0
2017-02-15,135.520,136.2700,134.6200,135.510,35623100.0,0.00,1.0,134.422269,135.166194,133.529559,134.412350,35623100.0
2017-02-16,135.670,135.9000,134.8398,135.345,22584555.0,0.00,1.0,134.571054,134.799191,133.747578,134.248686,22584555.0
2017-02-17,135.100,135.8300,135.1000,135.720,22198197.0,0.00,1.0,134.005671,134.729758,134.005671,134.620649,22198197.0
2017-02-21,136.230,136.7500,135.9800,136.700,24507156.0,0.00,1.0,135.126518,135.642306,134.878543,135.592711,24507156.0
2017-02-22,136.430,137.1200,136.1100,137.110,20836932.0,0.00,1.0,135.324898,136.009309,135.007490,135.999390,20836932.0
2017-02-23,137.380,137.4800,136.3000,136.530,20788186.0,0.00,1.0,136.267202,136.366392,135.195951,135.424088,20788186.0
2017-02-24,135.910,136.6600,135.2800,136.660,21776585.0,0.00,1.0,134.809110,135.553035,134.184213,135.553035,21776585.0
2017-02-27,137.140,137.4350,136.2800,136.930,20257426.0,0.00,1.0,136.029147,136.321757,135.176113,135.820848,20257426.0
2017-02-28,137.080,137.4350,136.7000,136.990,23482860.0,0.00,1.0,135.969633,136.321757,135.592711,135.880362,23482860.0
2017-03-01,137.890,140.1500,137.5950,139.790,36414585.0,0.00,1.0,136.773071,139.014765,136.480461,138.657681,36414585.0

In [5]:
order = pd.read_csv("order.csv", header=None, 
                    names=["command", "ticker", "vol"], 
                   parse_dates=True)
order.head()

            command  ticker   vol
date        command  ticker   vol
2017-02-17      BUY    AAPL  100
2017-02-17      BUY    AAPL  100
2017-02-17     SELL    AAPL   50
2017-02-17      BUY    GOOG   100

In [16]:
order.reset_index(inplace=True)
data.reset_index(inplace=True)
pd.merge(data, order, how='inner')

ValueError: cannot insert level_0, already exists

In [17]:
data.columns.

,index,Date,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
0,0,2017-01-03,115.800,116.3300,114.7600,116.150,28781865.0,0.00,1.0,114.369701,114.893155,113.342546,114.715378,28781865.0
1,1,2017-01-04,115.850,116.5100,115.7500,116.020,21118116.0,0.00,1.0,114.419083,115.070931,114.320318,114.586983,21118116.0
2,2,2017-01-05,115.920,116.8642,115.8100,116.610,22193587.0,0.00,1.0,114.488219,115.420756,114.379577,115.169696,22193587.0
3,3,2017-01-06,116.780,118.1600,116.4700,117.910,31751900.0,0.00,1.0,115.337596,116.700551,115.031425,116.453639,31751900.0
4,4,2017-01-09,117.950,119.4300,117.9400,118.990,33561948.0,0.00,1.0,116.493145,117.954865,116.483269,117.520300,33561948.0
5,5,2017-01-10,118.770,119.3800,118.3000,119.110,24462051.0,0.00,1.0,117.303017,117.905483,116.838822,117.638817,24462051.0
6,6,2017-01-11,118.740,119.9300,118.6000,119.750,27588593.0,0.00,1.0,117.273388,118.448689,117.135117,118.270913,27588593.0
7,7,2017-01-12,118.895,119.3000,118.2100,119.250,27086220.0,0.00,1.0,117.426473,117.826471,116.749934,117.777088,27086220.0
8,8,2017-01-13,119.110,119.6200,118.8100,119.040,26111948.0,0.00,1.0,117.638817,118.142518,117.342523,117.569682,26111948.0
9,9,2017-01-17,118.340,120.2400,118.2200,120.000,34439843.0,0.00,1.0,116.878328,118.754860,116.759810,118.517825,34439843.0
10,10,2017-01-18,120.000,120.5000,119.7100,119.990,23712961.0,0.00,1.0,118.517825,119.011649,118.231407,118.507948,23712961.0
11,11,2017-01-19,119.400,120.0900,119.3700,119.780,25597291.0,0.00,1.0,117.925236,118.606713,117.895606,118.300542,25597291.0
12,12,2017-01-20,120.450,120.4500,119.7346,120.000,32597892.0,0.00,1.0,118.962267,118.962267,118.255703,118.517825,32597892.0
13,13,2017-01-23,120.000,120.8100,119.7700,120.080,22050218.0,0.00,1.0,118.517825,119.317820,118.290666,118.596837,22050218.0
14,14,2017-01-24,119.550,120.1000,119.5000,119.970,23211038.0,0.00,1.0,118.073383,118.616590,118.024000,118.488195,23211038.0
15,15,2017-01-25,120.420,122.1000,120.2800,121.880,32586673.0,0.00,1.0,118.932637,120.591887,118.794366,120.374604,32586673.0
16,16,2017-01-26,121.670,122.4400,121.6000,121.940,26337576.0,0.00,1.0,120.167198,120.927687,120.098062,120.433863,26337576.0
17,17,2017-01-27,122.140,122.3500,121.6000,121.950,20562944.0,0.00,1.0,120.631393,120.838799,120.098062,120.443739,20562944.0
18,18,2017-01-30,120.930,121.6300,120.6600,121.630,30377503.0,0.00,1.0,119.436338,120.127692,119.169673,120.127692,30377503.0
19,19,2017-01-31,121.150,121.3900,120.6200,121.350,49200993.0,0.00,1.0,119.653620,119.890656,119.130167,119.851150,49200993.0
20,20,2017-02-01,127.030,130.4900,127.0100,128.750,111985040.0,0.00,1.0,125.460994,128.878258,125.441241,127.159749,111985040.0
21,21,2017-02-02,127.975,129.3900,127.7800,128.530,33710411.0,0.00,1.0,126.394322,127.791844,126.201730,126.942467,33710411.0
22,22,2017-02-03,128.310,129.1900,128.1600,129.080,24507301.0,0.00,1.0,126.725184,127.594315,126.577037,127.485673,24507301.0
23,23,2017-02-06,129.130,130.5000,128.9000,130.290,26845924.0,0.00,1.0,127.535056,128.888134,127.307897,128.680728,26845924.0
24,24,2017-02-07,130.540,132.0900,130.4500,131.530,38183841.0,0.00,1.0,128.927640,130.458496,128.838752,129.905412,38183841.0
25,25,2017-02-08,131.350,132.2200,131.2200,132.040,23004072.0,0.00,1.0,129.727636,130.586890,129.599241,130.409113,23004072.0
26,26,2017-02-09,131.650,132.4450,131.1200,132.420,28349859.0,0.57,1.0,130.583616,131.372177,130.057909,131.347379,28349859.0
27,27,2017-02-10,132.460,132.9400,132.0500,132.120,20065458.0,0.00,1.0,131.387055,131.863167,130.980376,131.049809,20065458.0
28,28,2017-02-13,133.080,133.8200,132.7500,133.290,23035421.0,0.00,1.0,132.002033,132.736039,131.674706,132.210332,23035421.0
29,29,2017-02-14,133.470,135.0900,133.2500,135.020,33226223.0,0.00,1.0,132.388874,133.995752,132.170656,133.926319,33226223.0
30,30,2017-02-15,135.520,136.2700,134.6200,135.510,35623100.0,0.00,1.0,134.422269,135.166194,133.529559,134.412350,35623100.0
31,31,2017-02-16,135.670,135.9000,134.8398,135.345,22584555.0,0.00,1.0,134.571054,134.799191,133.747578,134.248686,22584555.0
32,32,2017-02-17,135.100,135.8300,135.1000,135.720,22198197.0,0.00,1.0,134.005671,134.729758,134.005671,134.620649,22198197.0
33,33,2017-02-21,136.230,136.7500,135.9800,136.700,24507156.0,0.00,1.0,135.126518,135.642306,134.878543,135.592711,24507156.0
34,34,2017-02-22,136.430,137.1200,136.1100,137.110,20836932.0,0.00,1.0,135.324898,136.009309,135.007490,135.999390,20836932.0
35,35,2017-02-23,137.380,137.4800,136.3000,136.530,20788186.0,0.00,1.0,136.267202,136.366392,135.195951,135.424088,20788186.0
36,36,2017-02-24,135.910,136.6600,135.2800,136.660,21776585.0,0.00,1.0,134.809110,135.553035,134.184213,135.553035,21776585.0
37,37,2017-02-27,137.140,137.4350,136.2800,136.930,20257426.0,0.00,1.0,136.029147,136.321757,135.176113,135.820848,20257426.0
38,38,2017-02-28,137.080,137.4350,136.7000,136.990,23482860.0,0.00,1.0,135.969633,136.321757,135.592711,135.880362,23482860.0
39,39,2017-03-01,137.890,140.1500,137.5950,139.790,36414585.0,0.00,1.0,136.773071,139.014765,136.480461,138.657681,36414585.0